### ISSUE TITLE
Add a --no-realign option: if BAMs are given, don't convert them to FQs first

### ISSUE THREAD

**Issue by ihodes** [hammerlab/epidisco#138]

**Comment by smondet** [comment]
But where do the bams "join" the pipeline, do we re-do BQSR, indel-real, etc.?

Or should it be `--join-after {alignment,bqsr,mark-duplicates,...}`?

**Comment by armish** [comment]
cc'ing @julia326 and @timodonnell as they might provide more details on the rationale behind this request.

**Comment by julia326** [comment]
Some of the smoking sig project samples are BAMs containing both single- and paired-end reads, which errors during realignment. I've tried dropping single reads from the mixed files, but ran into issues because some marked-as-paired reads lack a mate in the BAM file. We'd like to skip the realignment step there, on the assumption that other parts of the epidisco pipeline (deduping, somatic variant calling) will work with mixed BAMs.
