### ISSUE TITLE
Filter for self-peptides

### ISSUE THREAD

**Issue by ihodes** [hammerlab/epidisco#39]

**Comment by hammer** [comment]
I think the right way to solve this problem is to have the filtering occur both in topiary and vaxrank
topiary should be useful as an endpoint for those that just want minimal epitopes
and self-peptides should be filtered out of the minimal epitopes
but then for those that want SLPs, we should also be filtering out any self peptides that may have been introduced into the larger 25mer or whatever

**Comment by iskandr** [comment]
Related issues: 
https://github.com/hammerlab/vaxrank/issues/31
https://github.com/hammerlab/vaxrank/issues/28
https://github.com/hammerlab/topiary/issues/62
and:
https://github.com/hammerlab/topiary/issues/49

**Comment by ihodes** [comment]
hah exact dup of vaxrank#28, will close

**Comment by smondet** [comment]
@ihodes I don't see the link with #28 ?

**Comment by ihodes** [comment]
update, meant hammerlab/vaxrank#28; guess this is the only issue in this repo

**Comment by ihodes** [comment]
This is done.
